export const usage = {
  adapter: "fixture",
  captured_at: 4_070_908_800,
  five_hour: { used_percent: 20, remaining_percent: 80, duration_minutes: 300, resets_at: 4_070_912_400 },
  weekly: { used_percent: 40, remaining_percent: 60, duration_minutes: 10080, resets_at: 4_071_513_600 },
};

const effort = (reasoningEffort: string) => ({ reasoningEffort, description: reasoningEffort });
const bounded = ["low", "medium", "high", "xhigh"];
const extended = [...bounded, "max", "ultra"];

export const modelCatalog = {
  source: "codex",
  warning: null,
  models: [
    { id: "gpt-6-astra", model: "gpt-6-astra", displayName: "GPT-6-Astra", description: "Frontier intelligence", defaultReasoningEffort: "low", supportedReasoningEfforts: extended.map(effort), isDefault: true, upgrade: null },
    { id: "gpt-6-sol", model: "gpt-6-sol", displayName: "GPT-6-Sol", description: "Workhorse model", defaultReasoningEffort: "medium", supportedReasoningEfforts: extended.map(effort), isDefault: false, upgrade: null },
    { id: "gpt-6-luna", model: "gpt-6-luna", displayName: "GPT-6-Luna", description: "Fast model", defaultReasoningEffort: "medium", supportedReasoningEfforts: [...bounded, "max"].map(effort), isDefault: false, upgrade: null },
    { id: "gpt-5.6-sol", model: "gpt-5.6-sol", displayName: "GPT-5.6-Sol", description: "Older coding model", defaultReasoningEffort: "low", supportedReasoningEfforts: extended.map(effort), isDefault: false, upgrade: "gpt-6-sol" },
    { id: "gpt-5.6-terra", model: "gpt-5.6-terra", displayName: "GPT-5.6-Terra", description: "Older balanced model", defaultReasoningEffort: "medium", supportedReasoningEfforts: extended.map(effort), isDefault: false, upgrade: "gpt-6-sol" },
    { id: "gpt-5.6-luna", model: "gpt-5.6-luna", displayName: "GPT-5.6-Luna", description: "Older fast model", defaultReasoningEffort: "medium", supportedReasoningEfforts: [...bounded, "max"].map(effort), isDefault: false, upgrade: "gpt-6-luna" },
  ],
};

export const tasks = [
  {
    id: "task-one",
    batch_id: "batch-one",
    title: "Fixture task",
    prompt: "Stored specification",
    success_criteria: "Fixture passes",
    cwd: "/tmp/project",
    run_at: 4_070_908_800,
    run_at_iso: "2099-01-01T00:00:00+00:00",
    position: 0,
    depends_on_task_id: null,
    dependency_type: "success",
    source_task_id: null,
    attempt_kind: null,
    attempt_number: 1,
    timezone: "UTC",
    difficulty: "standard",
    model: "gpt-5.6-terra",
    effort: "medium",
    permission_profile: "restricted",
    status: "scheduled",
    created_at: 4_070_000_000,
    updated_at: 4_070_000_000,
    last_error: null,
  },
  {
    id: "task-retry",
    batch_id: "batch-retry",
    title: "Failed fixture task",
    prompt: "Retry stored specification",
    success_criteria: "Retry fixture passes",
    cwd: "/tmp/project",
    run_at: 4_070_908_800,
    run_at_iso: "2099-01-01T00:00:00+00:00",
    position: 0,
    depends_on_task_id: null,
    dependency_type: "success",
    source_task_id: null,
    attempt_kind: null,
    attempt_number: 1,
    timezone: "UTC",
    difficulty: "standard",
    model: "gpt-5.6-terra",
    effort: "medium",
    permission_profile: "restricted",
    status: "failed",
    created_at: 4_070_000_000,
    updated_at: 4_070_000_100,
    last_error: "fixture failure",
  },
  {
    id: "task-two",
    batch_id: "batch-one",
    title: "Chained fixture task",
    prompt: "Continue the stored specification",
    success_criteria: "The chain passes",
    cwd: "/tmp/project",
    run_at: 4_070_908_800,
    run_at_iso: "2099-01-01T00:00:00+00:00",
    position: 1,
    depends_on_task_id: "task-one",
    dependency_type: "success",
    source_task_id: null,
    attempt_kind: null,
    attempt_number: 1,
    timezone: "UTC",
    difficulty: "standard",
    model: "gpt-5.6-terra",
    effort: "medium",
    permission_profile: "restricted",
    status: "scheduled",
    created_at: 4_070_000_000,
    updated_at: 4_070_000_000,
    last_error: null,
  },
  {
    id: "task-quota",
    batch_id: "batch-quota",
    title: "Quota fixture task",
    prompt: "Resume stored specification",
    success_criteria: "Quota fixture passes",
    cwd: "/tmp/project",
    run_at: 4_070_908_800,
    run_at_iso: "2099-01-01T00:00:00+00:00",
    position: 0,
    depends_on_task_id: null,
    dependency_type: "success",
    source_task_id: null,
    attempt_kind: null,
    attempt_number: 1,
    timezone: "UTC",
    difficulty: "complex",
    model: "gpt-5.6-sol",
    effort: "high",
    permission_profile: "networked",
    status: "quota_interrupted",
    created_at: 4_070_000_000,
    updated_at: 4_070_000_100,
    last_error: "quota interrupted",
  },
  {
    id: "task-completed",
    batch_id: "batch-completed",
    title: "Completed fixture task",
    prompt: "Already complete",
    success_criteria: "Done",
    cwd: "/tmp/project",
    run_at: 4_070_908_800,
    run_at_iso: "2099-01-01T00:00:00+00:00",
    position: 0,
    depends_on_task_id: null,
    dependency_type: "success",
    source_task_id: null,
    attempt_kind: null,
    attempt_number: 1,
    timezone: "UTC",
    difficulty: "simple",
    model: "gpt-5.6-luna",
    effort: "low",
    permission_profile: "restricted",
    status: "completed",
    created_at: 4_070_000_000,
    updated_at: 4_070_000_100,
    last_error: null,
  },
  {
    id: "task-running",
    batch_id: "batch-running",
    title: "Running fixture task",
    prompt: "Still running",
    success_criteria: "Eventually done",
    cwd: "/tmp/project",
    run_at: 4_070_908_800,
    run_at_iso: "2099-01-01T00:00:00+00:00",
    position: 0,
    depends_on_task_id: null,
    dependency_type: "success",
    source_task_id: null,
    attempt_kind: null,
    attempt_number: 1,
    timezone: "UTC",
    difficulty: "standard",
    model: "gpt-5.6-terra",
    effort: "medium",
    permission_profile: "restricted",
    status: "running",
    created_at: 4_070_000_000,
    updated_at: 4_070_000_100,
    last_error: null,
  },
  {
    id: "task-quota-unavailable",
    batch_id: "batch-quota-unavailable",
    title: "Unavailable quota task",
    prompt: "Retry after fixing Codex discovery",
    success_criteria: "Fresh retry succeeds",
    cwd: "/tmp/project",
    run_at: 4_070_908_800,
    run_at_iso: "2099-01-01T00:00:00+00:00",
    position: 0,
    depends_on_task_id: null,
    dependency_type: "success",
    source_task_id: null,
    attempt_kind: null,
    attempt_number: 1,
    timezone: "UTC",
    difficulty: "standard",
    model: "gpt-5.6-terra",
    effort: "medium",
    permission_profile: "restricted",
    status: "quota_skipped",
    created_at: 4_070_000_000,
    updated_at: 4_070_000_100,
    last_error: "quota telemetry unavailable: cannot start Codex app-server: No such file or directory (os error 2)",
  },
];

export const stats = {
  generated_at: 4_070_908_800,
  timezone: "UTC",
  last_week: { run_count: 3, tokens_used: 1200, tokens_unavailable_runs: 0 },
  last_month: { run_count: 3, tokens_used: 1200, tokens_unavailable_runs: 0 },
  last_year: { run_count: 3, tokens_used: 1200, tokens_unavailable_runs: 0 },
};

export const diagnostics = {
  schema_version: "1",
  overall: "warn",
  generated_at: 4_070_908_800,
  checks: [{ id: "service.state", status: "warn", summary: "Optional service is stopped" }],
};
